### ISSUE TITLE
Errors related to old dependencies

### ISSUE THREAD

**Issue by alekline** [HyperionGray/ng_modular_admin#3]
First, thank you so much for your work here. It is the only decent admin site for AngularDart (I was using "akveo ngx-admix" from Angular2 TS. Also, please sorry if this is not meant to be reported as an issue here

Trying to run the app as it is in the git repository, it seems that it is using old dependencies. I am using Dart SDK 2.3.0-edge.a1...

from your pubspec.yaml:

```
dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  sass_builder: ^2.1.2
```

```
ng_modular_admin $ webdev serve
webdev could not run for this project.
The `build_runner` version – 1.2.3 – is not within the allowed constraint – >=1.5.0 <2.0.0.
The `build_web_compilers` version – 0.4.4+3 – is not within the allowed constraint – >=1.2.0 <3.0.0.
```
Updating the dependencies in the pubspec.yaml to their latest versions...
```
dev_dependencies:
  build_runner: ^1.5.2
  test: ^1.0.0
  build_web_compilers: ^2.1.0
  sass_builder: ^2.1.3
```
...Generates other errors:
[SEVERE] Conflicting outputsBoth sass_builder:sass_builder and sass_builder:component_builder may output lib/src/components/side_nav_menu_header.css. Potential outputs must be unique across all builders. See https://github.com/dart-lang/build/blob/master/docs/faq.md#why-do-builders-need-unique-outputs

Thank you!
